### ISSUE TITLE
Intermittent freezes when running UU

### ISSUE THREAD

**Issue by alvaro-prieto** [timiimit/UT4UU-Public#14]
I'm sorry if the description isn't very detailed, but the only thing I've noticed is that when using UU I experience intermittent hangups throughout the game, especially during peak action. This is something that doesn't happen to me if I uninstall UU. I've tried it several times (currently using version 10). It is annoying so I have been forced to uninstall it again.

I'm playing on an iMac machine with bootcamp: OS Windows 10. Intel i5-9600K, 3.7GHz, 40Gb RAM, Radeon PRO 580X

**Comment by timiimit** [comment]
Sorry, i dont intend on supporting mac platform. I don't know what could be causing the issue as i have no clue about macs.
