### ISSUE TITLE
[Linux] Game crashes on v10.1.2 and v10.1.3

### ISSUE THREAD

**Issue by nesper8** [timiimit/UT4UU-Public#16]
**Describe the bug**
Game crashes when trying to launch any game mode on patch v10.1.2

**To Reproduce**
1. Open UT4 with the patch
2. Start any mode
3. Game crashes

**Expected behavior**
Match starts up correctly

**System Information (please complete the following information):**
 - OS: PikaOS 22.10 (Ubuntu 22.10 based)
 - Build Configuration: Game
 - Version: [v10.1.2](https://github.com/timiimit/UT4UU-Public/releases/tag/v10.1.2)

**Comment by nesper8** [comment]
[ut4.log](https://github.com/timiimit/UT4UU-Public/files/10377306/ut4.log)

**Comment by wof8317** [comment]
Can confirm that it is crashing on my Arch Linux as well. I could give an GDB output that can help, if needed.

**Comment by timiimit** [comment]
I have been busy lately. I'll check what could be going on as soon as i can.
In the mean time, if @wof8317 you can provide GDB backtrace at the point of exception and other relevant information, that would be helpful. tho, im not sure how much debug info there is in the binary that i released.

**Comment by wof8317** [comment]
[gdb.txt](https://github.com/timiimit/UT4UU-Public/files/10439810/gdb.txt)
Here is a GDB dump from UT4 with the latest UT4UU update.

**Comment by nesper8** [comment]
any updates on this?

**Comment by lan82art** [comment]
Hi, it crashes on Fedora37 as well, only with UT4UU update installed, I can play after uninstalling UT4UU only.

**Comment by timiimit** [comment]
Please let me know if [latest version](https://github.com/timiimit/UT4UU-Public/releases/tag/v10.1.3) fixes the problem.

**Comment by nesper8** [comment]
Just tried version 10.1.3 and looks like its not been resolved
i kinda figured out how to to use gdb so heres the gdb log and the backtrace
[gdb log.txt](https://github.com/timiimit/UT4UU-Public/files/10820463/gdb.log.txt)
[backtrace.txt](https://github.com/timiimit/UT4UU-Public/files/10820464/backtrace.txt)

**Comment by nesper8** [comment]
backtrace and gdb log for v10.1.4
[gdb log.txt](https://github.com/timiimit/UT4UU-Public/files/10891478/gdb.log.txt)
[bt.txt](https://github.com/timiimit/UT4UU-Public/files/10891481/bt.txt)

although i was able to finish one of the tutorial stages, the game crashes right after completion
i havent tested out normal matches tho

**Comment by nesper8** [comment]
I tried opening a single player bot match but it also crashes like pre 10.1.4 upon entering match lobby
gdb log and backtrace for those as well
[gdb log non training.txt](https://github.com/timiimit/UT4UU-Public/files/10891499/gdb.log.non.training.txt)
[bt non training.txt](https://github.com/timiimit/UT4UU-Public/files/10891501/bt.non.training.txt)

**Comment by nesper8** [comment]
Works fine with "upgrade social feature modules" disabled from the installer

**Comment by timiimit** [comment]
it would be useful if you entered console command `log LogHttp VeryVerbose` before attempting to reach a crash point. that would log more information.

**Comment by SuperSonic45** [comment]
I have same problem with v10.1.6 and OS Linux Mint 21.3 (Ubuntu 22.04 based).
[ut_4.log](https://github.com/timiimit/UT4UU-Public/files/14048900/ut_4.log)
