### ISSUE TITLE
Game will not Start.  Error MSG

### ISSUE THREAD

**Issue by EZT4rg3t** [timiimit/UT4UU-Public#20]
![UT4Error](https://user-images.githubusercontent.com/130467422/231164082-ef148ad3-de97-42b3-9288-530a2ade3c25.jpg)
When I try to fire up UT4 after running the UT4uu installer I get his msg and the game ends...  
Any Ideas?

Thanks

**Comment by timiimit** [comment]
*Resolved on discord*
