### ISSUE TITLE
Startup problems with UT4UU-v10_1_6

### ISSUE THREAD

**Issue by Reggei-g** [timiimit/UT4UU-Public#21]
**Describe the bug**
No profile or gaming data will be saved for both offline or online gaming
Create account seems to work fine (but there are probably some errors)
Note that both EPIC and Discord accounts works fine outside UT4UU

[OFFLINE ACCOUNT]
No profile has to be created for the offline account
The online account are created

Running offline
UT4 works fine after "install" from the RAR file but after install of UT4UU-v10_1_6 a problem occours.
Run UT4 local works but with an error message at startup: [UT could not save profile with MCP]
No profile and gaming will be saved, the game starts from beginning every time.

Running online
Probably the same error but the login problem starts after a few seconds when "Stalking your account" are shown
The startup are now running forever and need an manual "shutdown" from Windows

1. Go to 'desktop'
2. Click on 'UT4 startup icon' "C:\Unreal\UnrealTournament-4\Engine\Binaries\Win64\UE4-Win64-Shipping.exe UnrealTournament"
3. UT4UU "Accounts" is shown
4. Click on [OFFLINE ACCOUNT]
5. Click on Use-button
6. Welcome to "UT4UU Settings" window appears every startup
7. Click on Apply
8. UT4 starts fine
9. Click on Single Player Challenges
10. Only active available, click on one of them
11. click on Select difficulty
12. A warning shows up " You are not logged in. Any prograss you make on tihis challenge vill not be saved. Do you wish ti continue Yes/No
13. Click on Yes
14. The games runs now without saving

**Expected behavior**
Get the login to work.

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**System Information (please complete the following information):**
 - OS: Windows 11
 - Build Configuration:
 - Version  UT4UU-v10_1_6

**Additional context**
Probably the same login problem with online gaming account, it hangs up during file loading

**Comment by timiimit** [comment]
Offline account isnt really logging you into anything, it just allows you to play in offline mode. Based on the steps you listed, the outcome is expected. You have not logged into any online account, therefore it will tell you to log in.

EpicGames and Discord accounts have nothing to do with UT4. You need to log in with an account created on [new master server website](https://ut4.timiimit.com). And please follow [these instructions](https://ut4.timiimit.com/Instructions/UT4UU) to add your account. Before you can add accounts created on this website, you have to make sure game is configured to connect to it. Above instructions guide you with that.

**Comment by Reggei-g** [comment]
Thanks for your answer. I have made a new account on the new master server according to the guide but when I try to open the console it doesn't works with my non US keyboard, it's no tilde key there. How can i open the console ?

**Comment by timiimit** [comment]
You can change the key which can open console in settings. Top right cogwheel>Control Settings. And look for `Open Console` (or something similar).

**Comment by Reggei-g** [comment]
It works fine now execpt one thing. At the UT4UU log in/startup the "Waiting for funsies window" will hang for a long time,  more than 10 minutes. The only way I have found to handle this waiting is to wait or kill the UT4 process in windows. If I wait these 10 minutes everything starts up and it works fine to play. What to do?

**Comment by timiimit** [comment]
Step 2 in your original post suggests that your shortcut uses `"C:\Unreal\UnrealTournament-4\Engine\Binaries\Win64\UE4-Win64-Shipping.exe UnrealTournament"`. You are missing additional arguments. Specifically: `-epicapp=UnrealTournamentDev -epicenv=Prod -EpicPortal`. (I doubt its taking 10 min, its probably exactly 1 min)

**Comment by Reggei-g** [comment]
Thanks again, now it starts very fast.
